config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'posts/:post_id/comments/new'=> 'comments#new', as: :new_comment
  post 'posts/:post_id/comments'=> 'comments#create', as: :comments

  post 'posts/:id/:user_id/comments/upvote' => 'comments#upvote', as: :comment_upvote

  post 'posts/:id/:user_id/comments/downvote' => 'comments#downvote', as: :comment_downvote

  root 'posts#index'

  get 'posts' => 'posts#index', as: :posts

  get 'posts/new'=> 'posts#new', as: :new_post

  get 'posts/:id'=> 'posts#show', as: :post

  post 'posts/:id/:user_id/upvote' => 'posts#upvote', as: :upvote

  post 'posts/:id/:user_id/ownvote' => 'posts#downvote', as: :downvote

  post 'posts'=> 'posts#create'

  get 'users/new' => 'users#new', as: :new_user

  get 'users/:id' => 'users#show', as: :user

  post 'users'=> 'users#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # auto linked to albums table
  validates :post_id, presence: true
  validates :user_id, presence: true

  def scorevote
    upvote - downvote
  end


  belongs_to :post
  belongs_to :user
  # def artist
  # end

end

app/models/post.rb
class Post < ActiveRecord::Base
  # auto linked to comments table
  validates :user_id, presence: true

  has_many :comments
  belongs_to :user

  def scorevote
    upvote - downvote
  end


  # def albums
  #   []
  # end

  # def albums
  #   Album.where artist_id: @artist_id
  #   select * from albums where artist_id = @artist_id
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # auto linked to comments table

  has_many :comments
  has_many :posts

  def scorevote
    upvote - downvote
  end


  # def albums
  #   []
  # end

  # def albums
  #   Album.where artist_id: @artist_id
  #   select * from albums where artist_id = @artist_id
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find_by id: params[:id]
    @comment.post_id = params[:post_id]
  end

  def new
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.user_id = params[:user_id]

  end

  def create
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.user = params[:comment][:user]
    @comment.body = params[:comment][:body]
    @comment.user_id = params[:comment][:user_id]

    if @comment.save
      redirect_to post_path(id: @comment.post_id)
    else
      render :new
    end
  end


  def edit
  end

  def update
  end

  def upvote
    @comment = Comment.find_by id: params[:id]
    @user = User.find_by id: params[:user_id]
    @comment.upvote += 1
    @user.upvote += 1
      if @comment.save && @user.save
        redirect_to post_path(id: @comment.post_id)
      end
  end

  def downvote
    @comment = Comment.find_by id: params[:id]
    @user = User.find_by id: params[:user_id]
    @comment.downvote += 1
    @user.downvote += 1
      if @comment.save && @user.save
        redirect_to post_path(id: @comment.post_id)
      end
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    # @posts = Post.all.order("(upvote-downvote) DESC")

    @posts = Post.all.sort_by {|p| p.scorevote }.reverse
  end

  def show
    @post = Post.find_by id: params[:id]
    @user = User.find_by id: params[:id]
  end

  def new
    @post = Post.new
  end



  def create
    @post = Post.new
    @post.user_id = params[:post][:user_id]
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def upvote
    @post = Post.find_by id: params[:id]
    @user = User.find_by id: params[:user_id]
    @post.upvote += 1
    @user.upvote += 1
      if @post.save && @user.save
        redirect_to posts_path
      end
  end

  def downvote
    @post = Post.find_by id: params[:id]
    @user = User.find_by id: params[:user_id]
    @user.downvote += 1
    @post.downvote += 1
      if @post.save && @user.save
        redirect_to posts_path
      end
  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by id: params[:id]

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.username = params[:user][:username]
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Commenting on <%= @comment.post.title %></h1>

<%= form_for @comment do |f|  %>
  <%= f.label :user %>
  <%= f.collection_select :user_id, User.all, :id, :username, {prompt: true}, class: "form-control" %><br>
  <%= f.text_area :body %>

  <br>

  <%= f.submit %><br>  

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>





  <div class="top">
    <ul class="nav">
      <li class="active" role="presentation">my subreddits</li>

      <li role="presentation">Front-</li>
      <li role="presentation">All-</li>
      <li role="presentation">Random-</li>
      <li role="presentation">AskReddit-</li>
      <li role="presentation">worldnews-</li>
      <li role="presentation">funny-</li>
      <li role="presentation">pics-</li>
      <li role="presentation">news-</li>
      <li role="presentation">videos-</li>
      <li role="presentation">todayilearned-</li>
      <li role="presentation">gifs-</li>
      <li role="presentation">gaming-</li>
      <li role="presentation">aww-</li>
      <li role="presentation">Showerthoughts-</li>
      <li role="presentation">movies-</li>
      <li role="presentation">jokes-</li>
      <li role="presentation">mildlyinteresting-</li>
      <li role="presentation">dataisbeautiful-</li>
      <li role="presentation">nottheonion-</li>
      <li role="presentation">stufffff-</li>


    </ul>
  </div>
  <div class="Top-Header">

    <%= link_to root_path do %>
      <%= image_tag ("reddit-logo.png") %>
    <% end %>
      <ul class="nav">
        <li role="presentation" class="active"><a href="#">hot</a></li>
        <li role="presentation"><a href="/">new</a></li>
        <li role="presentation"><a href="/">rising</a></li>
        <li role="presentation"><a href="/">controversal</a></li>
        <li role="presentation"><a href="/">top</a></li>
        <li role="presentation"><a href="/">gilded</a></li>
        <li role="presentation"><a href="/">wiki</a></li>
        <li role="presentation"><a href="/">promoted</a></li>

    <div class="signin">
      <span class="user">Want to join? <%= link_to 'Log in or sign up', new_user_path %></a> in seconds.</span>

    </div>
  </ul>

</div><br>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div class="container">


  <div class="col-sm-9">
    <% @posts.each do |post| %>
      <div class="col-sm-12">


        <div class="col-sm-1">
          <%= link_to upvote_path(id: post.id, user_id: post.user_id), method: :post do %> <%= image_tag ("up.png") %><% end %>

          <%= post.scorevote %>

          <%= link_to downvote_path(id: post.id, user_id: post.user_id), method: :post do %><%= image_tag ("down.png") %><% end %>
        </div>


        <div class="col-sm-11">
          <%= link_to post.title, post_path(id: post.id) %><br>
           Submitted <%= post.created_at %> by <%= link_to post.user.username, user_path(id: post.user_id) %>
        </div>
      </div>


    <% end %>

    </div>


  <div class="col-sm-3">

    <%= link_to new_user_path do%>
      <%= image_tag ("signin.png") %>
    <% end %>
        <br>
    <%= image_tag ("ad1.jpg") %>
    <br>
    <%= link_to new_post_path do%>
      <%= image_tag ("newlink.png") %>
    <% end %>
    <br>

  <%= image_tag ("gold.png") %>

  </div>

</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_for @post do |f|  %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :user %>
  <%= f.collection_select :user_id, User.all, :id, :username, {prompt: true}, class: "form-control" %><br>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="col-sm-9">
    <div class="col-sm-12">
      <%= link_to 'Comment', new_comment_path(post_id: @post.id)%><br><br>
      <div class="col-sm-1">
        <%= link_to upvote_path(id: @post.id, user_id: @post.user_id), method: :post do %> <%= image_tag ("up.png") %><% end %>

        <%= @post.scorevote %>

        <%= link_to downvote_path(id: @post.id, user_id: @post.user_id), method: :post do %><%= image_tag ("down.png") %><% end %>

      </div>
      <div class="col-sm-11">
        <%= @post.title %><br>
        <%= link_to @post.user.username, user_path(id: @post.user_id) %> <br>
        <%= @post.body %> <br>

      </div>

    </div>

  </div>

  <div class="col-sm-3">
    <%= link_to new_user_path do%>
      <%= image_tag ("signin.png") %>
    <% end %>
    <br>
    <%= image_tag ("ad1.jpg") %>
    <br>
    <%= link_to new_post_path do%>
      <%= image_tag ("newlink.png") %>
    <% end %>
    <br>

    <%= image_tag ("gold.png") %>

  </div>

  <br>
  <div class="comments">

    <% @post.comments.each do |comment| %><br>
      <%= link_to comment_upvote_path(id: comment.id, user_id: comment.user_id), method: :post do %><%= image_tag ("up.png") %><% end %>

      <%= comment.scorevote %>

      <%= link_to comment_downvote_path(id: comment.id, user_id: comment.user_id), method: :post do %><%= image_tag ("down.png") %><% end %>

      <%= link_to comment.user.username, user_path(id: comment.user_id) %><br>
      <%= comment.body %><br><br>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f|  %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>


  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="item">
  <h3><%= @user.username %>'s Posts. Score: <%= @user.scorevote %> </h3>
  <% @user.posts.each do |post| %>
    <%= post.title %><br>
    <%= link_to post.user.username, user_path(id: post.user_id) %> <br>
    <%= post.body %> <br><br><br>
<% end %>

</div>
<br>
<h3> <%= @user.username %>'s comments on posts </h3>
<div class="comments">
    <% @user.comments.each do |comment| %>
    <%= comment.post.title %><br>
    <%= link_to comment.user.username, user_path(id: comment.user_id) %><br>
    <%= comment.body %><br><br>
    <% end %>
</div>